# -------------------------------------------------------------------------------------
#
# Copyright (c) 2023, WSO2 LLC. (http://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 LLC. and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained
# herein in any form is strictly forbidden, unless permitted by WSO2 expressly.
# You may not alter or remove any copyright or other notice from copies of this content.
#
# --------------------------------------------------------------------------------------

schedules:
- cron: '0 0 * * *'
  displayName: Daily midnight SCA build
  branches:
    include:
    - 'main'
    - 'choreo'

trigger:
  - none

pr:
  branches:
    include:
    - 'main'
    - 'choreo'

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
  - repository: templates
    type: github
    name: wso2-enterprise/azure-pipeline-templates
    endpoint: wso2-enterprise
  - repository: common-templates
    type: github
    name: wso2-enterprise/choreo-common-pipeline-templates
    endpoint: wso2-enterprise

jobs:
- job: sca_scan
  displayName: SCA scan
  variables:
  - group: 'choreo-sca-scan'
  steps:
  - template: ci-pipelines/templates/sca-scan.yaml@templates
    parameters:
      API_KEY: $(FOSSA-API-KEY)
      BRANCH: "main"
- job: notify_chat
  dependsOn: 
    - sca_scan
  condition: failed()
  displayName: Notify Chat Room
  variables:
  - group: 'microgateway-chat-credentials'
  steps:
  - template: notify-build-failures.yml@common-templates
    parameters:
      WEBHOOK_URL: $(CHAT_WEBHOOK_URL)
